In [6]:
import torch.nn as nn
import torch

In [4]:
loss = nn.CrossEntropyLoss()

In [7]:
input = torch.randn(3,5, requires_grad=True)

In [11]:
print(input)

tensor([[ 0.1498, -0.9261,  1.1537,  1.0525,  1.6167],
        [-1.8267, -0.8442,  0.5352,  1.5742,  2.0524],
        [ 2.3517,  1.4427,  0.5263,  0.5985,  0.3984]], requires_grad=True)


In [13]:
target = torch.empty(3, dtype=torch.long).random_(5)
print(target)

tensor([1, 4, 3])


In [9]:
output = loss(input,target)

In [10]:
output.backward()

In [9]:
# getting a,b for your truncated norm
loc = 0 #mean
scale = 0.5
myclip_a = -5
myclip_b = 5
a,b = (myclip_a - loc)/scale, (myclip_b - loc)/scale



In [ ]:

from scipy.stats import truncnorm
t2 = truncnorm.rvs(a,b, size = 200)
dfd = 78

In [1]:
from graph_world import World
world = World(10)

quad, seg = World.quadrant_circle_pair(world.locations[0], world.locations[5])

In [2]:
q

8 1


In [4]:
import torch

torch.cat([quad],seg)

TypeError: cat() received an invalid combination of arguments - got (int, int), but expected one of:
 * (tuple of Tensors tensors, int dim, *, Tensor out)
 * (tuple of Tensors tensors, name dim, *, Tensor out)


In [15]:
a = 5
c = 6
d = [a,c]
print(d)
d = torch.tensor(d)
print(d)

[5, 6]
tensor([5, 6])


In [17]:
a = 10
b = 17
print('a = {1} and b = {}'.format(ab))

ValueError: cannot switch from manual field specification to automatic field numbering